[font]
normal = { family = "Comic Mono", style = "Regular" }
bold = { family = "Comic Mono", style = "Bold" }
italic = { family = "Comic Mono", style = "Italic" }
bold_italic = { family = "Comic Mono", style = "Bold Italic" }
size = 14.0
offset = { x = 0, y = 2 }
glyph_offset = { x = 0, y = 1 }

[window]
padding = { x = 8, y = 8 }
dynamic_padding = true

[env]
TERM = "xterm-256color"
